services:
  - type: web
    name: tuly-backend
    env: node
    rootDir: tuly-shose-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 9999
      - key: MONGO_URI
        value: mongodb+srv://lucduong2002:lucduong2002@tulyshoe.bvwfdq6.mongodb.net/TULY_Shoe
      - key: JWT_SECRET
        value: your_secret_key
      - key: EMAIL_USER
        value: kubinduong2002@gmail.com
      - key: EMAIL_PASS
        value: wubr bysj fvrk rvju

  - type: static
    name: tuly-frontend
    rootDir: tuly-shose-frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://tulyshoe.onrender.com
